# Generated by Django 5.0.6 on 2024-07-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customizationinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproduct',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='size (in inches)'),
        ),
    ]
