# Generated by Django 5.0.6 on 2024-07-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_diamondproduct_size_silverproduct_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silverproduct',
            name='screw',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('south_screw', 'South screw'), ('regular_screw', 'Regular screw')], max_length=100, null=True, verbose_name='Screw type'),
        ),
    ]
