# Generated by Django 5.0.6 on 2024-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_silverproduct_screw'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproduct',
            name='fixed_mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
