# Generated by Django 5.0.6 on 2024-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_goldproduct_fixed_mrp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondproduct',
            name='fixed_mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='fixed_mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='goldproduct',
            name='fixed_mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
