# Generated by Django 5.0.6 on 2024-08-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_last_update_note_order_last_update_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_update_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_updated_by',
        ),
    ]
