# Generated by Django 5.0.6 on 2024-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_last_update_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(default=0, max_length=150, verbose_name='Pin Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=150, verbose_name='House No / House Name'),
        ),
    ]
