# Generated by Django 5.0.6 on 2024-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_address_pin_code_alter_address_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(default=0, max_length=150, verbose_name='Pin Code'),
        ),
    ]
