# Generated by Django 5.0.6 on 2024-08-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_address_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(default=0, max_length=150, verbose_name='Pin Code'),
        ),
    ]
