# Generated by Django 5.0.6 on 2024-08-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_address_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pin_code',
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=150, verbose_name='Nearest Location'),
        ),
    ]
