# Generated by Django 5.0.6 on 2024-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_address_pin_code_alter_address_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.CharField(default='000000', max_length=10, verbose_name='Pincode'),
        ),
    ]
