# Generated by Django 5.0.6 on 2024-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_address_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=10, verbose_name='Pincode'),
        ),
    ]
