# Generated by Django 5.0.6 on 2024-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_address_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationinquiry',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=150, verbose_name='House Name / House No'),
        ),
    ]
