# Generated by Django 5.0.6 on 2024-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customizationinquiry_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationinquiry',
            name='has_placed_order',
            field=models.BooleanField(default=False),
        ),
    ]
