# Generated by Django 5.0.6 on 2024-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_customizationinquiry_has_placed_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='admin_message',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Message'),
        ),
    ]
