# Generated by Django 5.0.6 on 2024-08-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_cart_admin_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='admin_message',
        ),
    ]
