# Generated by Django 5.0.6 on 2024-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_cart_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='admin_message',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Message'),
        ),
    ]
