# Generated by Django 4.2.15 on 2024-09-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_messagetemplate_messagelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageLog',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
