# Generated by Django 3.2.3 on 2024-09-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='message_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
